/**
    THIS IS GENERATED CODE AND SHOULD NOT BE CHANGED MANUALLY!!!

    Generated by: silvera
    Date: 2022-05-18 16:27:58
*/

package com.silvera.SciPaper.controller;

import java.util.Collection;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.cloud.context.config.annotation.RefreshScope;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.ResponseBody;
import javax.validation.Valid;

import com.silvera.SciPaper.service.base.ISciPaperService;
import com.silvera.SciPaper.domain.model.*;



@RefreshScope
@RestController
public class SciPaperController {

    @Autowired
    ISciPaperService sciPaperService;

    // Auto-generated CRUD methods
    
    
    
    @RequestMapping(value="/scipaper", method=RequestMethod.POST)
    @ResponseBody
    public SciPaper createSciPaper(@Valid @RequestBody SciPaper scipaper){
        return sciPaperService.createSciPaper(scipaper);
    }
    
    
    @RequestMapping(value="/scipaper/{id}", method=RequestMethod.PUT)
    @ResponseBody
    public SciPaper updateSciPaper(@PathVariable java.lang.String id, @Valid @RequestBody SciPaper scipaper){
        return sciPaperService.updateSciPaper(id, scipaper);
    }
    
    
    @RequestMapping(value="/scipaper/{id}", method=RequestMethod.GET)
    @ResponseBody
    public SciPaper readSciPaper(@PathVariable java.lang.String id){
        return sciPaperService.readSciPaper(id);
    }
    
    
    @RequestMapping(value="/scipaper/{id}", method=RequestMethod.DELETE)
    @ResponseBody
    public void deleteSciPaper(@PathVariable java.lang.String id){
        sciPaperService.deleteSciPaper(id);
    }
    
    



    
        
    

    @GetMapping(value="listscipapers")


    @ResponseBody
    public java.util.List<SciPaper> listSciPapers() {
        
        return sciPaperService.listSciPapers();

    }
    

}