/**
    THIS IS GENERATED CODE AND SHOULD NOT BE CHANGED MANUALLY!!!

    Generated by: silvera
    Date: 2022-05-19 13:06:03
*/

package com.silvera.SciPaper.domain.model;

import org.springframework.data.annotation.Id;
import javax.validation.constraints.*;
public class SciPaper {

    
    @Id
    private String id;
    
    
    
    @NotBlank(message="Field 'author' cannot be empty!")
    private java.lang.String author;
    
    
    @NotBlank(message="Field 'title' cannot be empty!")
    private java.lang.String title;
    
    
    @NotNull(message="Field 'sections' is mandatory!")
    private java.util.List<Section> sections= java.util.Collections.emptyList();
    
    private java.lang.Boolean published;


    
    public java.lang.String getAuthor() {
        return this.author;
    }

    public void setAuthor(java.lang.String author) {
        this.author = author;
    }
    
    public java.lang.String getTitle() {
        return this.title;
    }

    public void setTitle(java.lang.String title) {
        this.title = title;
    }
    
    public java.util.List<Section> getSections() {
        return this.sections;
    }

    public void setSections(java.util.List<Section> sections) {
        this.sections = sections;
    }
    

    
    public String getId(){
        return this.id;
    }
    
    public java.lang.Boolean getPublished() {
        return this.published;
    }

    public void setPublished(java.lang.Boolean published) {
        this.published = published;
    }
    

}