/**
    THIS IS GENERATED CODE AND SHOULD NOT BE CHANGED MANUALLY!!!

    Generated by: silvera
    Date: 2022-05-19 13:06:03
*/

package com.silvera.User.repository;

import com.silvera.User.domain.model.LoginInfo;
import org.springframework.data.mongodb.repository.MongoRepository;


public interface LoginInfoRepository extends MongoRepository<LoginInfo, java.lang.String> {
  // CRUD operations are included in MongoRepository interface

}