/**
    THIS IS GENERATED CODE AND SHOULD NOT BE CHANGED MANUALLY!!!

    Generated by: silvera
    Date: 2022-05-19 13:06:03
*/

package com.silvera.User.repository;

import com.silvera.User.domain.model.User;
import org.springframework.data.mongodb.repository.MongoRepository;


public interface UserRepository extends MongoRepository<User, java.lang.String> {
  // CRUD operations are included in MongoRepository interface
    User findByUsernameAndPassword(java.lang.String username, java.lang.String password);

    User findByUsername(java.lang.String username);

}