/**
    THIS IS GENERATED CODE AND SHOULD NOT BE CHANGED MANUALLY!!!

    Generated by: silvera
    Date: 2022-05-18 16:27:59
*/

package com.silvera.User.repository;

import com.silvera.User.domain.model.User;
import org.springframework.data.mongodb.repository.MongoRepository;


public interface UserRepository extends MongoRepository<User, java.lang.String> {
  // CRUD operations are included in MongoRepository interface

}