/**
    THIS IS GENERATED CODE AND SHOULD NOT BE CHANGED MANUALLY!!!

    Generated by: silvera
    Date: 2022-05-19 13:06:03
*/

package com.silvera.SciPaper.repository;

import com.silvera.SciPaper.domain.model.SciPaper;

import java.util.List;

import org.springframework.data.mongodb.repository.MongoRepository;


public interface SciPaperRepository extends MongoRepository<SciPaper, java.lang.String> {

    List<SciPaper> findAllByAuthor(java.lang.String author);
  // CRUD operations are included in MongoRepository interface

}