/**
    Use this file to implement business logic. This file will be preserved
    during next compilations.

    Generated by: silvera
    Date: 2022-05-18 16:27:58
*/

package com.silvera.SciPaper.service.impl;

import java.util.Optional;
import org.springframework.stereotype.Service;
import com.silvera.SciPaper.domain.model.*;
import com.silvera.SciPaper.repository.*;
import com.silvera.SciPaper.service.base.*;

import com.silvera.SciPaper.service.dependencies.*;

import org.springframework.beans.factory.annotation.Autowired;





@Service
public class SciPaperService implements ISciPaperService {

    
    @Autowired
    UserClient userClient;
    

    
    
    @Autowired
    SciPaperRepository scipaperRepository;
    

    public SciPaperService(){
        super();
    }

    // Auto-generated CRUD methods
    
    
    @Override
    public SciPaper createSciPaper(SciPaper scipaper){
        scipaperRepository.save(scipaper);
        Optional<SciPaper> opt = scipaperRepository.findById(scipaper.getId());
        return opt.orElse(null);
    }

    @Override
    public SciPaper updateSciPaper(java.lang.String id, SciPaper scipaperUpdate){
        SciPaper entity = this.readSciPaper(id);
        scipaperRepository.save(scipaperUpdate);
        return scipaperUpdate;
    }

    @Override
    public SciPaper readSciPaper(java.lang.String id){
        Optional<SciPaper> opt = scipaperRepository.findById(id);
        return opt.orElseThrow(IllegalArgumentException::new);
    }

    @Override
    public void deleteSciPaper(java.lang.String id){
        SciPaper entity = readSciPaper(id);
        scipaperRepository.delete(entity);
    }
    

    
    
    
    @Override
    public java.util.List<SciPaper> listSciPapers() {
        /*
            TODO: Implement this function!!!
        */
        throw new java.lang.UnsupportedOperationException("Not implemented yet.");
    }
    

}