# Generated by Django 4.0.4 on 2022-05-21 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='isLoggedId',
            new_name='loggedId',
        ),
    ]
