# Generated by Django 4.0.4 on 2022-05-21 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_isloggedid_user_loggedid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='loggedId',
            new_name='loggedIn',
        ),
    ]
