# Generated by Django 4.0.4 on 2022-05-21 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_rename_loggedid_user_loggedin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
