/**
    THIS IS GENERATED CODE AND SHOULD NOT BE CHANGED MANUALLY!!!

    Generated by: silvera
    Date: 2022-05-19 13:06:03
*/

package com.silvera.SciPaper.messages.publicationmsggroup;

import com.silvera.SciPaper.messages.Message;

public class PaperPublished extends Message {

    
    private java.lang.String sciPaperId;
    private java.lang.String title;
    private java.lang.String author;


    public PaperPublished(){
        this.name = "PublicationMsgGroup.PaperPublished";
    }
    public java.lang.String getSciPaperId() {
        return this.sciPaperId;
    }

    public void setSciPaperId(java.lang.String sciPaperId) {
        this.sciPaperId = sciPaperId;
    }
    
    public java.lang.String getTitle() {
        return this.title;
    }

    public void setTitle(java.lang.String title) {
        this.title = title;
    }
    
    public java.lang.String getAuthor() {
        return this.author;
    }

    public void setAuthor(java.lang.String author) {
        this.author = author;
    }
    

}