/**
    THIS IS GENERATED CODE AND SHOULD NOT BE CHANGED MANUALLY!!!

    Generated by: silvera
    Date: 2022-05-18 16:27:58
*/

package com.silvera.SciPaper.service.base;

import com.silvera.SciPaper.domain.model.*;


public interface ISciPaperService {

    // Auto-generated CRUD methods
    
    
    
    public SciPaper createSciPaper(SciPaper scipaper);
    
    
    public SciPaper updateSciPaper(java.lang.String id, SciPaper scipaperUpdate);
    
    
    public SciPaper readSciPaper(java.lang.String id);
    
    
    public void deleteSciPaper(java.lang.String id);
    
    


    
     
    
    public java.util.List<SciPaper> listSciPapers() ;
    

}