/**
    THIS IS GENERATED CODE AND SHOULD NOT BE CHANGED MANUALLY!!!

    Generated by: silvera
    Date: 2022-05-19 13:06:03
*/

package com.silvera.SciPaper.service.base;

import org.springframework.stereotype.Service;
import com.silvera.SciPaper.domain.model.*;
import com.silvera.SciPaper.messages.*;
import org.springframework.beans.factory.annotation.Autowired;


public interface ISciPaperService {

    // Auto-generated CRUD methods
    
    
    
    public SciPaper createSciPaper(SciPaper scipaper) throws java.lang.Exception;
    
    
    public SciPaper updateSciPaper(java.lang.String id, SciPaper scipaperUpdate);
    
    
    public SciPaper readSciPaper(java.lang.String id);
    
    
    public void deleteSciPaper(java.lang.String id);
    
    

    
    public java.util.List<SciPaper> listSciPapers(java.lang.String author) throws java.lang.Exception;
    
    public SciPaper publish(java.lang.String sciPaperId) throws java.lang.Exception;
    

    

}